version: '2'

services:
  locator1:
    # image: pidster/geode-runtime
    image: apachegeode/geode:1.0.0-incubating.M1
    hostname: v2_locator1_1
    network_mode: weave
    volumes:
      - ./scripts/:/scripts/
      - ./data/:/data/
    command: "/scripts/locator.sh"

  locator2:
    # image: pidster/geode-runtime
    image: apachegeode/geode:1.0.0-incubating.M1
    hostname: v2_locator2_1
    depends_on:
      - "locator1"
    network_mode: weave
    volumes:
      - ./scripts/:/scripts/
      - ./data/:/data/
    command: "/scripts/locator.sh"

  server:
    # image: pidster/geode-runtime
    image: apachegeode/geode:1.0.0-incubating.M1
    depends_on:
      - "locator1"
      - "locator2"
    network_mode: weave
    volumes:
      - ./scripts/:/scripts/
      - ./data/:/data/
    command: "/scripts/server.sh"
